ボリグングスコア計算（オブジェクト指向版）
kazumi3858/ruby-practices pull request #11
Opened 2022-04-19 03:47 UTC by kazumi3858

こんにちは。
ボウリング課題（オブジェクト指向版）を提出いたします。
ご確認よろしくお願いいたします🙏✨

2022-04-24 13:33 UTC, u1tnk requested changes
だいたい良いレベルになってきていますが、クラス構成に指摘がありますので、改善お願いします。

2022-04-24 13:33 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    @next_frame[0]
`@next_frame`が別のメソッドが変更したものを参照していますが、共有したインスタンス変数を別の箇所で強調して参照する形式はちょっと危険です。不要なメソッドでも触れてしまうので無用にスコープを広げてしまうことにもなりますし。

`@next_frame`と`@after_next_frame`はローカル変数にして引数で渡す形の方が良いかと思います。

2022-04-24 13:33 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +  def create_frames(numbers)
framesで終わっているメソッドでFrameというクラスがあるのに返すものがintegerの二次元配列であるのはNGです。
Shotインスタンス複数保持するFrameインスタンスを使うようにしましょう。

2022-04-24 13:33 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    @next_frame[0..1].sum
こちら8フレーム以前にストライクが連続したケースに対応できてないように見えるのですがどうでしょうか？

2022-04-25 09:17 UTC, kazumi3858 commented on 07.bowling_object/lib/game.rb
> +    @next_frame[0]
修正しました😄

2022-04-25 09:18 UTC, kazumi3858 commented on 07.bowling_object/lib/game.rb
> +    @next_frame[0..1].sum
`consecutive_strike_score`というメソッドの中で対応しております😸

2022-04-26 07:02 UTC, u1tnk requested changes
クラス構成は良くなったのですが、データを保持するようになったShot/Frameを有効に使えていません。
Gameクラスの責務が大きくなりすぎているのでFrameに渡せるところを探すと良いと思います。

2022-04-26 07:02 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    ninth_frame = index == 8
変数に入れてくれて分かりやすくなってるというのはありますが、すぐ上で一回だけなんで以下のように直接書いても良いかと思いました。

`index == 8 ? 10 + next_frame.second_shot : 10 + after_next_frame.first_shot`

あと、 10が共通なので


`10 + (index == 8 ? next_frame.second_shot : after_next_frame.first_shot)`

の方がもうちょっとスッキリするかもしれません。

2022-04-26 07:02 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    numbers = numbers.gsub('X', '10,NA').split(',')
問題は無いしこのプラクティスとしては十分合格なのですが、この一回NAに変換して後で削除するという方式はあまり綺麗では無いので合格した後にお手本を見て参考にしてください。

2022-04-26 07:02 UTC, u1tnk commented on 07.bowling_object/lib/shot.rb
> +    @number == 'X' ? 10 : @number.to_i
Xを 10,NAに置換してからShot.newしているのでこのメソッドがまったく意味が無くなってしまっています。

2022-04-26 07:02 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @first_shot = Shot.new(first_shot).score
せっかくデータを含んだShotクラスを作っているのにそのままscoreを使ってintegerにしてしまっては意味がありません。
Shotクラスのインスタンスで保持するようにしましょう。

2022-04-26 07:02 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    numbers = numbers.gsub('X', '10,NA').split(',')
上記のように思ったのですが、このままだとShotクラスのメソッドなどが有効に使えていないので練習の為にもXのままデータを保持するようにしてみましょう。

2022-04-26 07:04 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    divided_numbers.map do |shots|
ブロック変数とはいえ、shots変数に integerの配列になってしまっているのでshotクラスのインスタンスが来るようにするか、変数名を変更するようにしましょう。

2022-04-27 11:43 UTC, kazumi3858 commented on 07.bowling_object/lib/game.rb
> +    ninth_frame = index == 8
変数に入れるか迷ったのですが必要ないのですね😊
修正しました😸

2022-04-27 11:44 UTC, kazumi3858 commented on 07.bowling_object/lib/game.rb
> +    numbers = numbers.gsub('X', '10,NA').split(',')
修正しました😊

2022-04-27 11:44 UTC, kazumi3858 commented on 07.bowling_object/lib/game.rb
> +    divided_numbers.map do |shots|
変数名を変えました✨

2022-04-28 00:58 UTC, u1tnk requested changes

2022-04-28 00:58 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +      numbers.insert(index + 1, nil) if number == 'X'
NAよりアプローチとしては良いと思います 👍 
別件で、問題無く動いているようですが、ループの対象となっている配列をループ中に修正してしまうのはちょっと怖いですね。(rubyでは大丈夫のようですが、言語によってはエラーになったりします)
変換後のnumbersを入れる空配列を作って一個ずつコピーしていき、Xのときだけ追加でinsertすれば大丈夫です。
あと、返り値を使っているわけでも無いのに mapを使うのはおかしいのでeachにしましょう。

2022-04-28 00:58 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +  def strike
boolean(true/false)を返すメソッドは `strike?`と?を付けるのがrubyでの慣習なので付けましょう。

2022-04-28 00:58 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    score == 10
現状だとstrikeでもspare判定されてしまいます。
このコードだとstrikeチェックをした後に呼ばれるので問題無いのかもしれませんが、クラスを使う方が間違えないよう、便利なように配慮する観点からNGです。
そもそも spareですか？と聞いてstrikeのときにtrueを返すのはウソという観点からも修正するべきではあります 😅

2022-04-28 01:36 UTC, kazumi3858 commented on 07.bowling_object/lib/frame.rb
> +      numbers.insert(index + 1, nil) if number == 'X'
>ループの対象となっている配列をループ中に修正してしまうのはちょっと怖いですね。(rubyでは大丈夫のようですが、言語によってはエラーになったりします)

全く気にしていませんでした😯そうなんですね！
修正しました😸

2022-04-28 01:36 UTC, kazumi3858 commented on 07.bowling_object/lib/frame.rb
> +  def strike
修正しました😸

2022-04-28 01:37 UTC, kazumi3858 commented on 07.bowling_object/lib/frame.rb
> +    score == 10
おっしゃる通りです・・・😅😅
修正しました✨

2022-04-28 12:59 UTC, u1tnk requested changes
細かい件一点と今さら気づいたのですが、PRのタイトルを修正お願いします 🙏

2022-04-28 12:59 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    first_shot.score + second_shot.score == 10 unless strike?
細かいのですが、 booleanを期待していて trueとfalseと strikeのときだけ nilが返ってしまうのが気になります。
以下が良いかと思いました。

```
return false if strike?

first_shot.score + second_shot.score == 10
```

2022-04-29 00:07 UTC, kazumi3858 commented on 07.bowling_object/lib/frame.rb
> +    first_shot.score + second_shot.score == 10 unless strike?
なるほど
たしかにtrueとfalseが返ってきたほうが良いですね！😸
修正しました🙏

2022-04-29 03:12 UTC, u1tnk approved these changes
問題ありません。お疲れ様でした 👍

2022-04-29 05:20 UTC, merged