ボウリングのプログラムを作成
kazumi3858/ruby-practices pull request #3
Opened 2022-02-08 14:55 UTC by kazumi3858

2022-02-14 11:53 UTC, u1tnk requested changes

2022-02-14 11:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +scores = score.split(',')
複数系の変数は単数形の内容の配列になっているのが慣習なので、
scoreをsplitしたら scoresになるのちょっと不思議なのでscoreのところの名前を変えた方が良いですね。
この場合は
`scores = ARGV[0].split(',')`
のように変数にしないだけでも良いです。

2022-02-14 11:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  a = i + 1
aとbという変数名は意図が分からなくなるのでNGです。(iは慣習で分かるので大丈夫です)
内容にふさわしい変数名にしましょう。

2022-02-14 15:54 UTC, kazumi3858 commented on 04.bowling/bowling.rb
> +scores = score.split(',')
なるほど。名前の付け方難しいですね・・・
修正いたしました😭

2022-02-14 15:55 UTC, kazumi3858 commented on 04.bowling/bowling.rb
> +  a = i + 1
名前を分かりやすく修正しました😄
レビューありがとうございました。

2022-02-15 02:30 UTC, u1tnk requested changes

2022-02-15 02:30 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  next1 = i + 1
iはindexなので next_index の方が良いかなと思います 1と2だとちょっとまだ不親切なので。
英語で次の次は `after next` で良いようなので next2は `after_next_index`で良いかと思います。

2022-02-15 03:19 UTC, u1tnk approved these changes

2022-02-15 09:31 UTC, u1tnk approved these changes

2022-02-15 12:52 UTC, merged